/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author afif
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDissalary = new javax.swing.JButton();
        btnInfosalary = new javax.swing.JButton();
        btnInfoAtt = new javax.swing.JButton();
        btnInfoemp = new javax.swing.JButton();
        btnDisemp = new javax.swing.JButton();
        btnDisatt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Dashboard");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 11, -1, -1));

        btnDissalary.setText("Display Salary");
        btnDissalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDissalaryActionPerformed(evt);
            }
        });
        getContentPane().add(btnDissalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        btnInfosalary.setText("Info Salary");
        btnInfosalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfosalaryActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfosalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        btnInfoAtt.setText("Info Attendance");
        btnInfoAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoAttActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfoAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        btnInfoemp.setText("Info Employee");
        btnInfoemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoempActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfoemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        btnDisemp.setText("Display Employee");
        btnDisemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisempActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisemp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        btnDisatt.setText("Display Attendacne");
        btnDisatt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisattActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisatt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDissalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDissalaryActionPerformed
        new Display_salary().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDissalaryActionPerformed

    private void btnDisattActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisattActionPerformed
        new Display_attendence().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDisattActionPerformed

    private void btnDisempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisempActionPerformed
        new Display_emp().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDisempActionPerformed

    private void btnInfosalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfosalaryActionPerformed
        new Info_salary().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInfosalaryActionPerformed

    private void btnInfoAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoAttActionPerformed
        new Info_attendence().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInfoAttActionPerformed

    private void btnInfoempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoempActionPerformed
        new Info_emp().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInfoempActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisatt;
    private javax.swing.JButton btnDisemp;
    private javax.swing.JButton btnDissalary;
    private javax.swing.JButton btnInfoAtt;
    private javax.swing.JButton btnInfoemp;
    private javax.swing.JButton btnInfosalary;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
