/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import DataAccess.DataAccess;
import adbms.Emp;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author afif
 */
public class Display_emp extends javax.swing.JFrame {

    /**
     * Creates new form display_emp
     */
    
    private LinkedList<Emp> emps = new LinkedList<Emp>();
    DataAccess da = new DataAccess();
    
    
    public Display_emp() {
        initComponents();
        
        init();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSearch_disEmp = new javax.swing.JTextField();
        btnSearch_disEmp = new javax.swing.JButton();
        btnDone_disEmp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_disEmp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSearch_disEmp.setName("searchTxt_empinfo"); // NOI18N
        jPanel1.add(txtSearch_disEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 12, 109, -1));

        btnSearch_disEmp.setLabel("Go");
        btnSearch_disEmp.setName("searchBtn_empinfo"); // NOI18N
        btnSearch_disEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_disEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch_disEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 11, -1, -1));

        btnDone_disEmp.setText("Submit");
        btnDone_disEmp.setName("submitBtn_empinfo"); // NOI18N
        btnDone_disEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDone_disEmpActionPerformed(evt);
            }
        });
        jPanel1.add(btnDone_disEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, -1, -1));

        tbl_disEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane2.setViewportView(tbl_disEmp);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 370));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, 381));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearch_disEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_disEmpActionPerformed
        
        String search = txtSearch_disEmp.getText();
        
        search(search);
        
    }//GEN-LAST:event_btnSearch_disEmpActionPerformed

    private void btnDone_disEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDone_disEmpActionPerformed
        new dashboard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDone_disEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display_emp().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone_disEmp;
    private javax.swing.JButton btnSearch_disEmp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_disEmp;
    private javax.swing.JTextField txtSearch_disEmp;
    // End of variables declaration//GEN-END:variables

//    private void check() {
//        try {
//        DataAccess.DataHelper dh = new DataHelper();
//        ResultSet rs = dh.getAllData("dummy", "A","B");
//        
//        while(tblEmp_disEmp.getRowCount() > 0) 
//        {
//            ((DefaultTableModel) tblEmp_disEmp.getModel()).removeRow(0);
//        }
//        int columns = rs.getMetaData().getColumnCount();
//        while(rs.next())
//        {  
//            Object[] row = new Object[columns];
//            for (int i = 1; i <= columns; i++)
//            {  
//                row[i - 1] = rs.getObject(i);
//            }
//            ((DefaultTableModel) tblEmp_disEmp.getModel()).insertRow(rs.getRow()-1,row);
//        }
//
//        rs.close();
//        
//        }
//    catch(SQLException e)
//    {
//        System.out.println(e);
//    }
//}

    private void init() {
        
        
        emps = da.getAllEmp("EMP");
        System.out.println(emps);
        DefaultTableModel model = (DefaultTableModel) tbl_disEmp.getModel();
        model.setRowCount(0);
        String[] empheader = {"EMPNO","ENAME","PHONENO","ADDRESS","DEPTNO"};
        
        for (int i = 0; i < empheader.length; i++) {
            TableColumn column1 = tbl_disEmp.getTableHeader().getColumnModel().getColumn(i);
            column1.setHeaderValue(empheader[i]);
        }
        for (int i = 0; i < emps.size(); i++) {
            
            model.addRow(new Object[] {emps.get(i).getEmpno(), emps.get(i).getEname(),emps.get(i).getPhoneno(),
            emps.get(i).getAddress(),emps.get(i).getDeptno()});
        }
        
        
    }

    static boolean isNumber(String s) 
    { 
        for (int i = 0; i < s.length(); i++) 
        if (Character.isDigit(s.charAt(i))  
            == false) 
            return false; 
  
        return true; 
    } 
    private void search(String s) {
        
        if(isNumber(s)){
            emps = da.getAllEmp("EMP","EMPNO",s);
        }else{
            emps = da.getAllEmp("EMP","ENAME","'"+s+"'");
        }
        
        System.out.println(emps);
        DefaultTableModel model = (DefaultTableModel) tbl_disEmp.getModel();
        model.setRowCount(0);
        String[] empheader = {"EMPNO","ENAME","PHONENO","ADDRESS","DEPTNO"};
        
        for (int i = 0; i < empheader.length; i++) {
            TableColumn column1 = tbl_disEmp.getTableHeader().getColumnModel().getColumn(i);
            column1.setHeaderValue(empheader[i]);
        }
        for (int i = 0; i < emps.size(); i++) {
            
            model.addRow(new Object[] {emps.get(i).getEmpno(), emps.get(i).getEname(),emps.get(i).getPhoneno(),
            emps.get(i).getAddress(),emps.get(i).getDeptno()});
        }
    }

    
}
