/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import DataAccess.DataAccess;
import adbms.Attendance;
import adbms.Emp;
import com.toedter.calendar.JCalendar;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author afif
 */
public class Display_attendence extends javax.swing.JFrame {

    /**
     * Creates new form check_attendence
     */
    
    private LinkedList<Attendance> atts = new LinkedList<Attendance>();
    DataAccess da = new DataAccess();
    
    
    public Display_attendence() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAtt_disAtt = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSearch_disAtt = new javax.swing.JButton();
        btnDone_disAtt = new javax.swing.JButton();
        jLocaleChooser1 = new com.toedter.components.JLocaleChooser();
        clndr_DisAtt = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAtt_disAtt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tblAtt_disAtt.setName("tbl_checkattendance"); // NOI18N
        jScrollPane1.setViewportView(tblAtt_disAtt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 330));

        jLabel1.setText("Search");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, -1, -1));

        btnSearch_disAtt.setText("Go");
        btnSearch_disAtt.setName("searchBtn_checkattendance"); // NOI18N
        btnSearch_disAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_disAttActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch_disAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 60, 20));

        btnDone_disAtt.setText("Done");
        btnDone_disAtt.setName("DoneBtn_checkattendance"); // NOI18N
        jPanel1.add(btnDone_disAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 320, 90, -1));
        jPanel1.add(jLocaleChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));
        jPanel1.add(clndr_DisAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 30, 280, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 347));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearch_disAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_disAttActionPerformed
        JCalendar j = new JCalendar();
        //String s = clndr_DisAtt.;
    }//GEN-LAST:event_btnSearch_disAttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display_attendence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone_disAtt;
    private javax.swing.JButton btnSearch_disAtt;
    private com.toedter.calendar.JCalendar clndr_DisAtt;
    private javax.swing.JLabel jLabel1;
    private com.toedter.components.JLocaleChooser jLocaleChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAtt_disAtt;
    // End of variables declaration//GEN-END:variables

    private void init() {
        atts = da.getAllAttendance("ATTENDANCE");
        System.out.println(atts);
        DefaultTableModel model = (DefaultTableModel) tblAtt_disAtt.getModel();
        model.setRowCount(0);
        String[] empheader = {"SNO","STATUS","DATE","REASON","EMPNO"};
        
        for (int i = 0; i < empheader.length; i++) {
            TableColumn column1 = tblAtt_disAtt.getTableHeader().getColumnModel().getColumn(i);
            column1.setHeaderValue(empheader[i]);
        }
        for (int i = 0; i < atts.size(); i++) {
            
            model.addRow(new Object[] {atts.get(i).getSno(), atts.get(i).getStatus(),atts.get(i).getAtt_date(),
            atts.get(i).getReason(),atts.get(i).getEmpno()});
        }
    }
}
