/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import DataAccess.DataAccess;
import adbms.Emp;
import adbms.Salary;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author afif
 */
public class Display_salary extends javax.swing.JFrame {

    private LinkedList<Salary> sals = new LinkedList<Salary>();
    DataAccess da = new DataAccess();
    /**
     * Creates new form check_salary
     */
    public Display_salary() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSearch_disSalary = new javax.swing.JTextField();
        btnSearch_disSalary = new javax.swing.JButton();
        btnDone_disSalary = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalary_disSalary = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSearch_disSalary.setName("searchTxt_checksalary"); // NOI18N

        btnSearch_disSalary.setLabel("Go");
        btnSearch_disSalary.setName("searchBtn_checksalary"); // NOI18N
        btnSearch_disSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_disSalaryActionPerformed(evt);
            }
        });

        btnDone_disSalary.setText("Done");
        btnDone_disSalary.setName("doneBtn_checksalary"); // NOI18N
        btnDone_disSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDone_disSalaryActionPerformed(evt);
            }
        });

        jLabel1.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSearch_disSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch_disSalary)))
                        .addContainerGap())
                    .addComponent(btnDone_disSalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch_disSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch_disSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDone_disSalary))
        );

        tblSalary_disSalary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSalary_disSalary.setName("tbl_checksalary"); // NOI18N
        jScrollPane1.setViewportView(tblSalary_disSalary);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDone_disSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDone_disSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDone_disSalaryActionPerformed

    private void btnSearch_disSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_disSalaryActionPerformed
        String s = txtSearch_disSalary.getText();
        search(s);
    }//GEN-LAST:event_btnSearch_disSalaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display_salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone_disSalary;
    private javax.swing.JButton btnSearch_disSalary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSalary_disSalary;
    private javax.swing.JTextField txtSearch_disSalary;
    // End of variables declaration//GEN-END:variables

    private void init() {
        sals = da.getAllSalary("SALARY");
        System.out.println(sals);
        DefaultTableModel model = (DefaultTableModel) tblSalary_disSalary.getModel();
        model.setRowCount(0);
        String[] empheader = {"AMOUNT","DATE_FROM","DATE_TO","EMPNO"};
        
        for (int i = 0; i < empheader.length; i++) {
            TableColumn column1 = tblSalary_disSalary.getTableHeader().getColumnModel().getColumn(i);
            column1.setHeaderValue(empheader[i]);
        }
        for (int i = 0; i < sals.size(); i++) {
            
            model.addRow(new Object[] {sals.get(i).getAmount(), sals.get(i).getDate_from(),sals.get(i).getDate_to(),
            sals.get(i).getEmpno(),sals.get(i).getStatus()});
        }
    }

    private void search(String s) {
        sals = da.getAllSalary("SALARY","EMPNO",s);
        System.out.println(sals);
        DefaultTableModel model = (DefaultTableModel) tblSalary_disSalary.getModel();
        model.setRowCount(0);
        String[] empheader = {"AMOUNT","DATE_FROM","DATE_TO","EMPNO"};
        
        for (int i = 0; i < empheader.length; i++) {
            TableColumn column1 = tblSalary_disSalary.getTableHeader().getColumnModel().getColumn(i);
            column1.setHeaderValue(empheader[i]);
        }
        for (int i = 0; i < sals.size(); i++) {
            model.addRow(new Object[] {sals.get(i).getAmount(), sals.get(i).getDate_from(),sals.get(i).getDate_to(),
            sals.get(i).getEmpno()});
        }
    }
}
