/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import DataAccess.DataAccess;
import adbms.Salary;
import javax.swing.JOptionPane;

/**
 *
 * @author afif
 */
public class Info_salary extends javax.swing.JFrame {

    DataAccess da = new DataAccess();
    Salary s = new Salary();
    
    /**
     * Creates new form Info_salary
     */
    public Info_salary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtEmpno_infoSalary = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbStatus_infoSalary = new javax.swing.JComboBox();
        btnInsert_infoSalary = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        clndrTo_infoSalary = new com.toedter.calendar.JCalendar();
        btnUpdate_infoSalary = new javax.swing.JButton();
        btnDelete_infoSalary = new javax.swing.JButton();
        btnDone_infoSalary = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        clndrFrom_infoSalary = new com.toedter.calendar.JCalendar();
        jLabel6 = new javax.swing.JLabel();
        txtAmount_infoSalary = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Employee No");
        jLabel4.setName("SerialNo_label"); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtEmpno_infoSalary.setName("empnoTxt_insertatten"); // NOI18N
        jPanel2.add(txtEmpno_infoSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 145, -1));

        jLabel5.setText("Status");
        jLabel5.setName("SerialNo_label"); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        cbStatus_infoSalary.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paid", "Unpaid", "Hold" }));
        cbStatus_infoSalary.setName("statusCb_insertatt"); // NOI18N
        jPanel2.add(cbStatus_infoSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 145, -1));

        btnInsert_infoSalary.setText("insert");
        btnInsert_infoSalary.setName("insertBtn_insertatt"); // NOI18N
        btnInsert_infoSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert_infoSalaryActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsert_infoSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, -1, -1));

        jLabel7.setText("pay date to");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));
        jPanel2.add(clndrTo_infoSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 320, -1));

        btnUpdate_infoSalary.setText("update");
        btnUpdate_infoSalary.setName("updateBtn_insertatt"); // NOI18N
        btnUpdate_infoSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate_infoSalaryActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate_infoSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 650, -1, -1));

        btnDelete_infoSalary.setText("delete");
        btnDelete_infoSalary.setName("deleteBtn_insertatt"); // NOI18N
        btnDelete_infoSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete_infoSalaryActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete_infoSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 650, -1, -1));

        btnDone_infoSalary.setText("Done");
        btnDone_infoSalary.setName("doneBtn_insertatt"); // NOI18N
        btnDone_infoSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDone_infoSalaryActionPerformed(evt);
            }
        });
        jPanel2.add(btnDone_infoSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, -1, -1));

        jLabel8.setText("pay date from");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel2.add(clndrFrom_infoSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 320, -1));

        jLabel6.setText("salary amount");
        jLabel6.setName("SerialNo_label"); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, -1));

        txtAmount_infoSalary.setName("empnoTxt_insertatten"); // NOI18N
        jPanel2.add(txtAmount_infoSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 145, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdate_infoSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate_infoSalaryActionPerformed
        s.setEmpno(Integer.parseInt(txtEmpno_infoSalary.getText()));
            s.setAmount(Integer.parseInt(txtAmount_infoSalary.getText()));
            int day=clndrFrom_infoSalary.getDayChooser().getDay();
            int month=clndrFrom_infoSalary.getMonthChooser().getMonth()+1;
            int year=clndrFrom_infoSalary.getYearChooser().getYear();
            String datefrom=year+"-"+month+"-"+day;
            System.out.println(datefrom);
            int day1=clndrTo_infoSalary.getDayChooser().getDay();
            int month1=clndrTo_infoSalary.getMonthChooser().getMonth()+1;
            int year1=clndrTo_infoSalary.getYearChooser().getYear();
            String dateto=year1+"-"+month1+"-"+day1;
            System.out.println(dateto);
            s.setDate_from(datefrom);
            s.setDate_to(dateto);
            s.setStatus(cbStatus_infoSalary.getSelectedItem().toString());
            da.update_salary(s);
    }//GEN-LAST:event_btnUpdate_infoSalaryActionPerformed

    private void btnDelete_infoSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete_infoSalaryActionPerformed
        JOptionPane.showMessageDialog(null, "select date from calendar to delete record");
        int day=clndrFrom_infoSalary.getDayChooser().getDay();
        int month=clndrFrom_infoSalary.getMonthChooser().getMonth()+1;
        int year=clndrFrom_infoSalary.getYearChooser().getYear();
        String datefrom=year+"-"+month+"-"+day;
        System.out.println(datefrom);
        s.setDate_from(datefrom);
        da.delete_salary(s);
            
    }//GEN-LAST:event_btnDelete_infoSalaryActionPerformed

    private void btnDone_infoSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDone_infoSalaryActionPerformed
        new dashboard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDone_infoSalaryActionPerformed

    private void btnInsert_infoSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert_infoSalaryActionPerformed
        if(txtEmpno_infoSalary.getText().isEmpty()){
            txtEmpno_infoSalary.requestFocus();
            JOptionPane.showMessageDialog(null, "enter empno");
        }else if(txtAmount_infoSalary.getText().isEmpty()){
            txtAmount_infoSalary.requestFocus();
            JOptionPane.showMessageDialog(null, "enter salary amount");             
        }else{
            s.setEmpno(Integer.parseInt(txtEmpno_infoSalary.getText()));
            s.setAmount(Integer.parseInt(txtAmount_infoSalary.getText()));
            int day=clndrFrom_infoSalary.getDayChooser().getDay();
            int month=clndrFrom_infoSalary.getMonthChooser().getMonth()+1;
            int year=clndrFrom_infoSalary.getYearChooser().getYear();
            String datefrom=year+"-"+month+"-"+day;
            System.out.println(datefrom);
            int day1=clndrTo_infoSalary.getDayChooser().getDay();
            int month1=clndrTo_infoSalary.getMonthChooser().getMonth()+1;
            int year1=clndrTo_infoSalary.getYearChooser().getYear();
            String dateto=year1+"-"+month1+"-"+day1;
            System.out.println(dateto);
            s.setDate_from(datefrom);
            s.setDate_to(dateto);
            s.setStatus(cbStatus_infoSalary.getSelectedItem().toString());
            da.insert_salary(s);
            
        }
        
        
        
    }//GEN-LAST:event_btnInsert_infoSalaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info_salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete_infoSalary;
    private javax.swing.JButton btnDone_infoSalary;
    private javax.swing.JButton btnInsert_infoSalary;
    private javax.swing.JButton btnUpdate_infoSalary;
    private javax.swing.JComboBox cbStatus_infoSalary;
    private com.toedter.calendar.JCalendar clndrFrom_infoSalary;
    private com.toedter.calendar.JCalendar clndrTo_infoSalary;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtAmount_infoSalary;
    private javax.swing.JTextField txtEmpno_infoSalary;
    // End of variables declaration//GEN-END:variables
}
