/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import DataAccess.DataAccess;
import adbms.Attendance;
import javax.swing.JOptionPane;

/**
 *
 * @author afif
 */
public class Info_attendence extends javax.swing.JFrame {

    DataAccess da = new DataAccess();
    Attendance a = new Attendance();
    
    /**
     * Creates new form Info_attendance
     */
    public Info_attendence() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtEmpno_infoAtt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtReason_infoAtt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbStatus_infoAtt = new javax.swing.JComboBox();
        btnInsert_infoAtt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        clndr_infoAtt = new com.toedter.calendar.JCalendar();
        btnUpdate_infoAtt = new javax.swing.JButton();
        btnDelete_infoAtt = new javax.swing.JButton();
        btnDone_infoAtt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Employee No");
        jLabel4.setName("SerialNo_label"); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, -1, -1));

        txtEmpno_infoAtt.setName("empnoTxt_insertatten"); // NOI18N
        jPanel2.add(txtEmpno_infoAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 14, 145, -1));

        jLabel5.setText("Status");
        jLabel5.setName("SerialNo_label"); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        txtReason_infoAtt.setName("reasonTxt_insertatten"); // NOI18N
        jPanel2.add(txtReason_infoAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 94, 240, 41));

        jLabel6.setText("Reason");
        jLabel6.setName("SerialNo_label"); // NOI18N
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));

        cbStatus_infoAtt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "present", "absent" }));
        cbStatus_infoAtt.setName("statusCb_insertatt"); // NOI18N
        jPanel2.add(cbStatus_infoAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 145, -1));

        btnInsert_infoAtt.setText("insert");
        btnInsert_infoAtt.setName("insertBtn_insertatt"); // NOI18N
        btnInsert_infoAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsert_infoAttActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsert_infoAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel7.setText("select  date");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 175, -1, -1));
        jPanel2.add(clndr_infoAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 167, 310, -1));

        btnUpdate_infoAtt.setText("Update");
        btnUpdate_infoAtt.setName("updateBtn_insertatt"); // NOI18N
        btnUpdate_infoAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate_infoAttActionPerformed(evt);
            }
        });
        jPanel2.add(btnUpdate_infoAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, -1, -1));

        btnDelete_infoAtt.setText("delete");
        btnDelete_infoAtt.setName("deleteBtn_insertatt"); // NOI18N
        btnDelete_infoAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete_infoAttActionPerformed(evt);
            }
        });
        jPanel2.add(btnDelete_infoAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        btnDone_infoAtt.setText("Done");
        btnDone_infoAtt.setName("doneBtn_insertatt"); // NOI18N
        btnDone_infoAtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDone_infoAttActionPerformed(evt);
            }
        });
        jPanel2.add(btnDone_infoAtt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDelete_infoAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete_infoAttActionPerformed
        int day=clndr_infoAtt.getDayChooser().getDay();
        int month=clndr_infoAtt.getMonthChooser().getMonth()+1;
        int year=clndr_infoAtt.getYearChooser().getYear();
        String dateNow=year+"-"+month+"-"+day;
        System.out.println(dateNow);
        JOptionPane.showMessageDialog(null, "selet date from calendar to delete data");
        
//      a.setEmpno(Integer.parseInt(txtEmpno_infoAtt.getText()));
        a.setAtt_date(dateNow);
        da.delete_attendance(a);
        
    }//GEN-LAST:event_btnDelete_infoAttActionPerformed

    private void btnUpdate_infoAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate_infoAttActionPerformed
        int day=clndr_infoAtt.getDayChooser().getDay();
        int month=clndr_infoAtt.getMonthChooser().getMonth()+1;
        int year=clndr_infoAtt.getYearChooser().getYear();
        String dateNow=year+"-"+month+"-"+day;
        System.out.println(dateNow);
        a.setEmpno(Integer.parseInt(txtEmpno_infoAtt.getText()));
        a.setStatus(cbStatus_infoAtt.getSelectedItem().toString());
        a.setAtt_date(dateNow);
        a.setReason(txtReason_infoAtt.getText());
        a.setAtt_date(dateNow);
        da.update_attendace(a);
    }//GEN-LAST:event_btnUpdate_infoAttActionPerformed

    private void btnDone_infoAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDone_infoAttActionPerformed
        new dashboard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnDone_infoAttActionPerformed

    private void btnInsert_infoAttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsert_infoAttActionPerformed
        int day=clndr_infoAtt.getDayChooser().getDay();
        int month=clndr_infoAtt.getMonthChooser().getMonth()+1;
        int year=clndr_infoAtt.getYearChooser().getYear();
        String dateNow=year+"-"+month+"-"+day;
        System.out.println(dateNow);
        a.setEmpno(Integer.parseInt(txtEmpno_infoAtt.getText()));
        a.setStatus(cbStatus_infoAtt.getSelectedItem().toString());
        a.setAtt_date(dateNow);
        a.setReason(txtReason_infoAtt.getText());
        
        da.insert_attendance(a);
    }//GEN-LAST:event_btnInsert_infoAttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Info_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Info_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Info_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Info_attendence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Info_attendence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete_infoAtt;
    private javax.swing.JButton btnDone_infoAtt;
    private javax.swing.JButton btnInsert_infoAtt;
    private javax.swing.JButton btnUpdate_infoAtt;
    private javax.swing.JComboBox cbStatus_infoAtt;
    private com.toedter.calendar.JCalendar clndr_infoAtt;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtEmpno_infoAtt;
    private javax.swing.JTextField txtReason_infoAtt;
    // End of variables declaration//GEN-END:variables
}
